// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
// ```dart
// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo3Do8c1Bqn3NgSioQjeWQZB47gBrNeT0',
    appId: '1:20350234511:web:5804ce45b38be492f3e5fa',
    messagingSenderId: '20350234511',
    projectId: 'colorfultrashgame',
    authDomain: 'colorfultrashgame.firebaseapp.com',
    storageBucket: 'colorfultrashgame.firebasestorage.app',
    measurementId: 'G-XR1MNNDE42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhGeQ_gtmjfHTnPrbNccQ66eqXMjWEnmA',
    appId: '1:20350234511:android:0163605154ceeabcf3e5fa',
    messagingSenderId: '20350234511',
    projectId: 'colorfultrashgame',
    storageBucket: 'colorfultrashgame.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLjA1515VE6TGfAMMAazBbIchd1uAPnlA',
    appId: '1:20350234511:ios:2df974bb5dbe9f78f3e5fa',
    messagingSenderId: '20350234511',
    projectId: 'colorfultrashgame',
    storageBucket: 'colorfultrashgame.firebasestorage.app',
    iosBundleId: 'com.example.colorfulTrashGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLjA1515VE6TGfAMMAazBbIchd1uAPnlA',
    appId: '1:20350234511:ios:2df974bb5dbe9f78f3e5fa',
    messagingSenderId: '20350234511',
    projectId: 'colorfultrashgame',
    storageBucket: 'colorfultrashgame.firebasestorage.app',
    iosBundleId: 'com.example.colorfulTrashGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo3Do8c1Bqn3NgSioQjeWQZB47gBrNeT0',
    appId: '1:20350234511:web:7c28baa3006ea72af3e5fa',
    messagingSenderId: '20350234511',
    projectId: 'colorfultrashgame',
    authDomain: 'colorfultrashgame.firebaseapp.com',
    storageBucket: 'colorfultrashgame.firebasestorage.app',
    measurementId: 'G-Y4RWH9VV8E',
  );
}
